import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MainPage from "../src/MainPage/MainPage.jsx";
import Navbar from "../src/Navbar/Navbar";
import Info from "../src/Info/Info";
import Footer from "../src/Footer/Footer";
import Parallaxx from "../src/Parallax/Parallaxx";
import Documents from "../src/Documents/Documents";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Хлорелла</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/public/images/first.jpg" /> */}
      </Head>

      <Navbar />
      <main className={styles.main}>
        <MainPage />
        <Info />
        <Parallaxx />
        <Documents />
      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
}
