import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MainPage from "../src/MainPage/MainPage.jsx";
import Navbar from "../src/Navbar/Navbar";
import Info from "../src/Info/Info";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Хлорелла</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <MainPage />
        <Info />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
